### ISSUE TITLE
wifi conection error

### ISSUE THREAD

**Issue by rmorteza21** [Codworth/esp-host#16]
hi
i use your hen for custumers
i use d1 mini
i have error in wifi conection
is random
for example i use one d1 mini for run hen in many consoles
and random cant connect to wifi and show error
for example in 10 console cant connect to 2 console
i think is internal fw issue because if i write old 4.55 hen i can connect to all 10 console
sorry for my bad english
and thank you for work :)

**Comment by Codworth** [comment]
I have limited to 3 active connections in the code, I did not test stability beyond that.
